// Kurirana mapa lucide ikona (kebab-naziv → komponenta).
// Registrujemo samo ikone koje koristimo → čuva tree-shaking.
// Dodaj nove po potrebi; BaseIcon ih razrješava po nazivu.
import {
  ArrowRight,
  ArrowLeft,
  Search,
  Menu,
  X,
  Tag,
  MapPin,
  Calendar,
  CalendarPlus,
  Clock,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Check,
  CircleCheck,
  CircleAlert,
  Info,
  Sparkles,
  Phone,
  Mail,
  Globe,
  Facebook,
  Instagram,
  Youtube,
  Upload,
  SlidersHorizontal,
  Hourglass,
  Hammer,
  UtensilsCrossed,
  Wrench,
  Trees,
  Landmark,
  BedDouble,
  Star,
  Inbox,
  Image,
  Building2,
  Briefcase,
  BookOpen,
  User,
  Play,
  Maximize2,
  Ticket,
  Send,
  Map,
  List,
  ExternalLink,
  Target,
  Users,
  Store,
  PenLine,
  Heart,
  Leaf,
  Camera,
  Quote,
  Share2,
  Compass,
  FileText,
  Megaphone,
  Settings,
  Pencil,
  Trash2,
  Bold,
  Italic,
  Heading,
  Link2,
  LogIn,
  LogOut,
  Eye,
  EyeOff,
  Lock,
  AtSign,
  Bell,
  Plus,
  PenTool,
  Clock3,
} from 'lucide-vue-next'

export const icons = {
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  search: Search,
  menu: Menu,
  x: X,
  tag: Tag,
  'map-pin': MapPin,
  calendar: Calendar,
  'calendar-plus': CalendarPlus,
  clock: Clock,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  check: Check,
  'circle-check': CircleCheck,
  'circle-alert': CircleAlert,
  info: Info,
  sparkles: Sparkles,
  phone: Phone,
  mail: Mail,
  globe: Globe,
  facebook: Facebook,
  instagram: Instagram,
  youtube: Youtube,
  upload: Upload,
  filter: SlidersHorizontal,
  hourglass: Hourglass,
  // kategorije (mapa/filteri)
  zanat: Hammer,
  hrana: UtensilsCrossed,
  usluge: Wrench,
  priroda: Trees,
  kultura: Landmark,
  smjestaj: BedDouble,
  dogadjaj: Calendar,
  star: Star,
  inbox: Inbox,
  image: Image,
  'building-2': Building2,
  briefcase: Briefcase,
  'book-open': BookOpen,
  user: User,
  play: Play,
  maximize: Maximize2,
  ticket: Ticket,
  send: Send,
  map: Map,
  list: List,
  'external-link': ExternalLink,
  target: Target,
  users: Users,
  store: Store,
  pen: PenLine,
  heart: Heart,
  leaf: Leaf,
  camera: Camera,
  quote: Quote,
  share: Share2,
  compass: Compass,
  'file-text': FileText,
  megaphone: Megaphone,
  settings: Settings,
  pencil: Pencil,
  'trash-2': Trash2,
  bold: Bold,
  italic: Italic,
  heading: Heading,
  link: Link2,
  'log-in': LogIn,
  'log-out': LogOut,
  eye: Eye,
  'eye-off': EyeOff,
  lock: Lock,
  'at-sign': AtSign,
  bell: Bell,
  plus: Plus,
  'pen-tool': PenTool,
  'clock-3': Clock3,
}
